/**
 * conex.io REST-Like API
 * The conex.io API provides the functionality to interact with home automation devices, which are connected to a home automation server, detached from the manufacturer specific communication syntax.
 *
 * OpenAPI spec version: 0.9.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Filter {
  
  @SerializedName("device_ids")
  private List<String> deviceIds = null;
  @SerializedName("room_ids")
  private List<String> roomIds = null;
  @SerializedName("group_ids")
  private List<String> groupIds = null;
  @SerializedName("function_ids")
  private List<String> functionIds = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getDeviceIds() {
    return deviceIds;
  }
  public void setDeviceIds(List<String> deviceIds) {
    this.deviceIds = deviceIds;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getRoomIds() {
    return roomIds;
  }
  public void setRoomIds(List<String> roomIds) {
    this.roomIds = roomIds;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getGroupIds() {
    return groupIds;
  }
  public void setGroupIds(List<String> groupIds) {
    this.groupIds = groupIds;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getFunctionIds() {
    return functionIds;
  }
  public void setFunctionIds(List<String> functionIds) {
    this.functionIds = functionIds;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Filter filter = (Filter) o;
    return (this.deviceIds == null ? filter.deviceIds == null : this.deviceIds.equals(filter.deviceIds)) &&
        (this.roomIds == null ? filter.roomIds == null : this.roomIds.equals(filter.roomIds)) &&
        (this.groupIds == null ? filter.groupIds == null : this.groupIds.equals(filter.groupIds)) &&
        (this.functionIds == null ? filter.functionIds == null : this.functionIds.equals(filter.functionIds));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.deviceIds == null ? 0: this.deviceIds.hashCode());
    result = 31 * result + (this.roomIds == null ? 0: this.roomIds.hashCode());
    result = 31 * result + (this.groupIds == null ? 0: this.groupIds.hashCode());
    result = 31 * result + (this.functionIds == null ? 0: this.functionIds.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Filter {\n");
    
    sb.append("  deviceIds: ").append(deviceIds).append("\n");
    sb.append("  roomIds: ").append(roomIds).append("\n");
    sb.append("  groupIds: ").append(groupIds).append("\n");
    sb.append("  functionIds: ").append(functionIds).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
